# docker-kafka

# 启动 docker-compose -f docker-compose.yml up

version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: unless-stopped # 当发生错误时重启
    hostname: zoo1
    ports:
      - "2181:2181"

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.241.122.251
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # 默认创建的topic
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    volumes:
      - ./data/kafka1/data:/data
      - ./data/kafka1/log:/datalog
    depends_on:
      - zookeeper

  kafka2:
    container_name: kafka2
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      # ipconfig getifaddr en0 指令的结果
      KAFKA_ADVERTISED_HOST_NAME: 10.241.122.251
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/data
      - ./data/kafka1/log:/datalog
    depends_on:
      - zookeeper