version: '3.1'

services:
  db:
    image: mysql
    restart: unless-stopped
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog
      MYSQL_USER: 'test'
      MYSQL_PASS: 'yourpassword'
    volumes:
    - ./data:/var/lib/mysql
    - ./conf:/etc/mysql/conf.d
    - ./conf/my.cnf:/etc/my.cnf
    # 数据库还原目录 可将需要还原的sql文件放在这里
    - ./source:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    container_name: docker-mysql

